'use client';

import { useEffect, useState } from 'react';
import { useSupabaseClient } from '@supabase/auth-helpers-react';

type UserRow = {
  id: string;
  username: string;
  accuracy: number;
  total_score: number;
};

// const firstNames = [
//   'Aisha',
//   'Mateo',
//   'Yuki',
//   'Fatima',
//   'Liam',
//   'Sofia',
//   'Wei',
//   'Priya',
//   'Omar',
//   'Anya',
//   'Lucas',
//   'Mina',
//   'Jin',
//   'Sara',
//   'Diego',
//   'Leila',
//   'Ivan',
//   'Noor',
//   'Hana',
//   'Ravi',
//   'Elena',
//   'Tariq',
//   'Maya',
//   'Sven',
//   'Chloe',
//   'Zara',
//   'Niko',
//   'Amir',
//   'Ines',
//   'Kofi',
//   'Santiago',
//   'Aya',
//   'Marek',
//   'Lina',
//   'Bao',
//   'Nadia',
//   'Samir',
//   'Tessa',
//   'Yara',
//   'Hugo',
//   'Amina',
//   'Kenji',
//   'Isla',
//   'Farid',
//   'Lucia',
//   'Oksana',
//   'Rosa',
//   'Jorge',
//   'Sibel',
//   'Dara',
//   'Marta',
//   'Soren',
//   'Ava',
//   'Nia',
//   'Tomas',
//   'Lale',
//   'Rami',
//   'Mila',
//   'Yusuf',
//   'Sami',
//   'Laleh',
//   'Elias',
//   'Nina',
//   'Omarion',
//   'Suri',
//   'Kian',
//   'Lior',
//   'Sana',
//   'Rashid',
//   'Alya',
//   'John',
//   'Elliot',
//   'Will',
//   'William',
//   'Tyler',
// ];

// const lastNames = [
//   'Kim',
//   'Patel',
//   'Nguyen',
//   'Garcia',
//   'Smith',
//   'Chen',
//   'Khan',
//   'Ivanov',
//   'Dubois',
//   'Singh',
//   'Yamamoto',
//   'Ali',
//   'Fernandez',
//   'Lee',
//   'Hernandez',
//   'Kowalski',
//   'Silva',
//   'Ahmed',
//   'Novak',
//   'Wong',
//   'Bakir',
//   'Santos',
//   'Müller',
//   'Haddad',
//   'Popov',
//   'Moreno',
//   'Rossi',
//   'Bianchi',
//   'Kumar',
//   'Zhou',
//   'Petrov',
//   'Costa',
//   'Rahman',
//   'Schmidt',
//   'López',
//   'Tanaka',
//   'Jansen',
//   'Kaya',
//   'Sato',
//   'Moreau',
//   'Gonzalez',
//   'Hassan',
//   'Mendes',
//   'Dimitrov',
//   'Cruz',
//   'Mori',
//   'Khalil',
//   'Borges',
//   'Ivanova',
//   'Mei',
//   'Suleiman',
//   'Park',
//   'Bauer',
//   'Sokolov',
//   'Nakamura',
//   'Barros',
//   'Mamedov',
//   'Zhang',
//   'Yilmaz',
//   'Pereira',
//   'Smith',
//   'Johnson',
//   'James',
//   'Brown',
//   'Jones',
//   'Peterson',
//   'Green',
// ];

// const SEED = 1;

// function seededRandom(seed: number) {
//   const x = Math.sin(seed + SEED) * 10000;
//   return x - Math.floor(x);
// }

// function getSeededUsername(idx: number) {
//   const first = firstNames[Math.floor(seededRandom(idx) * firstNames.length)];
//   const last =
//     lastNames[Math.floor(seededRandom(idx + 1000) * lastNames.length)];
//   const rand = seededRandom(idx + 2000);
//   if (rand < 0.7) {
//     return `${first} ${last}`;
//   } else if (rand < 0.9) {
//     return `${first}${last}${Math.floor(seededRandom(idx + 3000) * 1000)}`;
//   } else {
//     return `${first}_${last}`;
//   }
// }

// const SAMPLE_USERS: UserRow[] = Array.from({ length: 300 }).map((_, idx) => ({
//   id: `sample${idx + 1}`,
//   username: getSeededUsername(idx),
//   accuracy: parseFloat((seededRandom(idx + 4000) * 100).toFixed(2)),
//   total_score: Math.floor(seededRandom(idx + 5000) * 81),
// }));

const SAMPLE_USERS: UserRow[] = [
  { id: 'sample1', username: 'James Smith', accuracy: 98.2, total_score: 83 },
  { id: 'sample2', username: 'Mary Johnson', accuracy: 87, total_score: 75 },
  { id: 'sample3', username: 'John Williams', accuracy: 92.5, total_score: 73 },
  { id: 'sample4', username: 'Patricia Brown', accuracy: 85, total_score: 70 },
  { id: 'sample5', username: 'Robert Jones', accuracy: 90.1, total_score: 68 },
  { id: 'sample6', username: 'Jennifer Garcia', accuracy: 78, total_score: 67 },
  {
    id: 'sample7',
    username: 'Michael Miller',
    accuracy: 88.7,
    total_score: 66,
  },
  { id: 'sample8', username: 'Linda Davis', accuracy: 80, total_score: 65 },
  {
    id: 'sample9',
    username: 'William Rodriguez',
    accuracy: 95.6,
    total_score: 64,
  },
  {
    id: 'sample10',
    username: 'Elizabeth Martinez',
    accuracy: 82,
    total_score: 63,
  },
  {
    id: 'sample11',
    username: 'David Hernandez',
    accuracy: 76.4,
    total_score: 62,
  },
  { id: 'sample12', username: 'Barbie', accuracy: 84, total_score: 61 },
  {
    id: 'sample13',
    username: 'Richard Gonzalez',
    accuracy: 91.8,
    total_score: 60,
  },
  { id: 'sample14', username: 'Susan Wilson', accuracy: 77, total_score: 59 },
  {
    id: 'sample15',
    username: 'Joseph Anderson',
    accuracy: 89.5,
    total_score: 58,
  },
  { id: 'sample16', username: 'Jessica Thomas', accuracy: 83, total_score: 57 },
  {
    id: 'sample17',
    username: 'Thomas Taylor',
    accuracy: 86.9,
    total_score: 56,
  },
  { id: 'sample18', username: 'Sarah Moore', accuracy: 80, total_score: 55 },
  {
    id: 'sample19',
    username: 'Charles Jackson',
    accuracy: 93.2,
    total_score: 54,
  },
  { id: 'sample20', username: 'Karen Martin', accuracy: 75, total_score: 53 },
  {
    id: 'sample21',
    username: 'Christopher Lee',
    accuracy: 88.1,
    total_score: 52,
  },
  { id: 'sample22', username: 'Nancy Perez', accuracy: 79, total_score: 51 },
  {
    id: 'sample23',
    username: 'Daniel Thompson',
    accuracy: 90.7,
    total_score: 50,
  },
  { id: 'sample24', username: 'Lisa White', accuracy: 82, total_score: 49 },
  {
    id: 'sample25',
    username: 'Matthew Harris',
    accuracy: 85.3,
    total_score: 48,
  },
  { id: 'sample26', username: 'Betty Sanchez', accuracy: 77, total_score: 47 },
  {
    id: 'sample27',
    username: 'Anthony Clark',
    accuracy: 92.9,
    total_score: 46,
  },
  {
    id: 'sample28',
    username: 'Margaret Ramirez',
    accuracy: 80,
    total_score: 45,
  },
  { id: 'sample29', username: 'Mark Lewis', accuracy: 87.6, total_score: 44 },
  {
    id: 'sample30',
    username: 'Sandra Robinson',
    accuracy: 81,
    total_score: 43,
  },
  {
    id: 'sample31',
    username: 'Donald Walker',
    accuracy: 89.2,
    total_score: 42,
  },
  { id: 'sample32', username: 'Ashley Young', accuracy: 76, total_score: 41 },
  { id: 'sample33', username: 'Steven Allen', accuracy: 91.4, total_score: 40 },
  { id: 'sample34', username: 'Kimberly King', accuracy: 83, total_score: 39 },
  { id: 'sample35', username: 'Paul Wright', accuracy: 86.7, total_score: 38 },
  { id: 'sample36', username: 'Emily Scott', accuracy: 80, total_score: 37 },
  {
    id: 'sample37',
    username: 'Andrew Torres',
    accuracy: 94.5,
    total_score: 36,
  },
  { id: 'sample38', username: 'Donna Nguyen', accuracy: 78, total_score: 35 },
  { id: 'sample39', username: 'Joshua Hill', accuracy: 88.9, total_score: 34 },
  { id: 'sample40', username: 'Melissa Flores', accuracy: 82, total_score: 33 },
  {
    id: 'sample41',
    username: 'Kenneth Green',
    accuracy: 90.3,
    total_score: 32,
  },
  { id: 'sample42', username: 'Deborah Adams', accuracy: 75, total_score: 31 },
  { id: 'sample43', username: 'Kevin Nelson', accuracy: 87.2, total_score: 30 },
  {
    id: 'sample44',
    username: 'Stephanie Baker',
    accuracy: 81,
    total_score: 29,
  },
  { id: 'sample45', username: 'Brian Hall', accuracy: 85.8, total_score: 28 },
  { id: 'sample46', username: 'Rebecca Rivera', accuracy: 77, total_score: 27 },
  {
    id: 'sample47',
    username: 'George Campbell',
    accuracy: 92.1,
    total_score: 26,
  },
  {
    id: 'sample48',
    username: 'Sharon Mitchell',
    accuracy: 80,
    total_score: 25,
  },
  {
    id: 'sample49',
    username: 'Edward Carter',
    accuracy: 89.7,
    total_score: 24,
  },
  { id: 'sample50', username: 'Laura Roberts', accuracy: 83, total_score: 23 },
  { id: 'sample51', username: 'James Smith', accuracy: 97, total_score: 22 },
  {
    id: 'sample52',
    username: 'Mary Johnson',
    accuracy: 87,
    total_score: 21,
  },
  { id: 'sample53', username: 'JohnW illiams', accuracy: 92, total_score: 20 },
  {
    id: 'sample54',
    username: 'Patricia Brown',
    accuracy: 80,
    total_score: 20,
  },
  { id: 'sample55', username: 'RobertJ ones', accuracy: 92, total_score: 30 },
  {
    id: 'sample56',
    username: 'Jennifer Garcia',
    accuracy: 78.6,
    total_score: 17,
  },
  {
    id: 'sample57',
    username: 'Michael Miller',
    accuracy: 88,
    total_score: 16,
  },
  { id: 'sample58', username: 'Linda Davis', accuracy: 80.9, total_score: 15 },
  {
    id: 'sample59',
    username: 'William',
    accuracy: 95,
    total_score: 140,
  },
  {
    id: 'sample60',
    username: 'Elizabeth Martinez',
    accuracy: 82.3,
    total_score: 58,
  },
  {
    id: 'sample61',
    username: 'David Hernandez',
    accuracy: 76,
    total_score: 112,
  },
  {
    id: 'sample62',
    username: 'Barbarian',
    accuracy: 84.7,
    total_score: 111,
  },
  {
    id: 'sample63',
    username: 'Richard Gonzalez',
    accuracy: 91,
    total_score: 10,
  },
  {
    id: 'sample64',
    username: 'Susan Wilson',
    accuracy: 77.2,
    total_score: 30,
  },
  {
    id: 'sample65',
    username: 'Joseph Anderson',
    accuracy: 89,
    total_score: 38,
  },
  {
    id: 'sample66',
    username: 'Jessica Thomas',
    accuracy: 70,
    total_score: 7,
  },
  { id: 'sample67', username: 'Thomas Taylor', accuracy: 60, total_score: 6 },
  { id: 'sample68', username: 'Sarah Moore', accuracy: 80, total_score: 13 },
  {
    id: 'sample69',
    username: 'Charles Jackson',
    accuracy: 93,
    total_score: 23,
  },
  {
    id: 'sample70',
    username: 'KarenMartin_20',
    accuracy: 30,
    total_score: 3,
  },
  { id: 'sample71', username: 'ChrisLee', accuracy: 20, total_score: 2 },
  { id: 'sample72', username: 'Dana Peezr', accuracy: 10, total_score: 1 },
  { id: 'sample73', username: 'DanThompson33', accuracy: 90, total_score: 90 },
  { id: 'sample74', username: 'Lisa White', accuracy: 82.7, total_score: 79 },
  { id: 'sample75', username: 'Matt.Harris', accuracy: 85, total_score: 78 },
  { id: 'sample76', username: 'Mookie Betts', accuracy: 77.8, total_score: 77 },
  { id: 'sample77', username: 'Tony Clark', accuracy: 92, total_score: 76 },
  {
    id: 'sample78',
    username: 'MaggieRamirez',
    accuracy: 80.2,
    total_score: 75,
  },
  { id: 'sample79', username: 'Marcus Morris', accuracy: 87, total_score: 74 },
  {
    id: 'sample80',
    username: 'Sandy Robinson',
    accuracy: 81.5,
    total_score: 73,
  },
  { id: 'sample81', username: 'DonWalker', accuracy: 89, total_score: 72 },
  { id: 'sample82', username: 'Ashley$Young', accuracy: 76.3, total_score: 71 },
  { id: 'sample83', username: 'Steve Allen', accuracy: 91, total_score: 70 },
  { id: 'sample84', username: 'Kim King', accuracy: 83.6, total_score: 69 },
  { id: 'sample85', username: 'Paul Wright', accuracy: 86, total_score: 68 },
  { id: 'sample86', username: 'Emily Scott', accuracy: 80.8, total_score: 67 },
  { id: 'sample87', username: 'Andy Torres', accuracy: 94, total_score: 66 },
  { id: 'sample88', username: 'Donna Nguyen', accuracy: 78.3, total_score: 65 },
  { id: 'sample89', username: 'Josh Hill', accuracy: 88, total_score: 64 },
  {
    id: 'sample90',
    username: 'Michael Jordan',
    accuracy: 82.1,
    total_score: 63,
  },
  { id: 'sample91', username: 'Ken Green', accuracy: 90, total_score: 62 },
  { id: 'sample92', username: 'Wemby', accuracy: 75.2, total_score: 61 },
  { id: 'sample93', username: 'Kev', accuracy: 87, total_score: 60 },
  { id: 'sample94', username: 'Steph', accuracy: 81.7, total_score: 59 },
  { id: 'sample95', username: 'Joshy', accuracy: 85, total_score: 58 },
  { id: 'sample96', username: 'Edward Im', accuracy: 77.9, total_score: 57 },
  { id: 'sample97', username: 'Campbell', accuracy: 92, total_score: 56 },
  { id: 'sample98', username: 'Shawn Marion', accuracy: 80.6, total_score: 55 },
  { id: 'sample99', username: 'Ed Carter', accuracy: 89, total_score: 54 },
  {
    id: 'sample100',
    username: 'Laura Roberts',
    accuracy: 83.2,
    total_score: 53,
  },
  {
    id: 'sample101',
    username: 'Brandon Murphy',
    accuracy: 84.5,
    total_score: 52,
  },
  {
    id: 'sample102',
    username: 'Tiffany Brooks',
    accuracy: 91,
    total_score: 60,
  },
  {
    id: 'sample103',
    username: 'Eric Simmons',
    accuracy: 77.2,
    total_score: 44,
  },
  { id: 'sample104', username: 'Crystal Reed', accuracy: 88, total_score: 58 },
  { id: 'sample105', username: 'Dylan Price', accuracy: 80, total_score: 49 },
  {
    id: 'sample106',
    username: 'Brittany Powell',
    accuracy: 86.8,
    total_score: 55,
  },
  { id: 'sample107', username: 'Shawn Foster', accuracy: 93, total_score: 63 },
  {
    id: 'sample108',
    username: 'Courtney Barnes',
    accuracy: 79.1,
    total_score: 47,
  },
  {
    id: 'sample109',
    username: 'Trevor Reed_12',
    accuracy: 82,
    total_score: 51,
  },
  {
    id: 'sample110',
    username: 'Megan Patterson',
    accuracy: 90.6,
    total_score: 59,
  },
  {
    id: 'sample111',
    username: 'Austin Russell',
    accuracy: 75,
    total_score: 41,
  },
  {
    id: 'sample112',
    username: 'Hailey Griffin',
    accuracy: 87.3,
    total_score: 56,
  },
  { id: 'sample113', username: 'Zachary Hayes', accuracy: 81, total_score: 48 },
  { id: 'sample114', username: 'Jenna Ford', accuracy: 89.9, total_score: 61 },
  { id: 'sample115', username: 'Cody Butler', accuracy: 78, total_score: 45 },
  { id: 'sample116', username: 'Morgan Webb', accuracy: 85.7, total_score: 53 },
  { id: 'sample117', username: 'Sierra Grant', accuracy: 92, total_score: 62 },
  { id: 'sample118', username: 'Blake Perry', accuracy: 80.4, total_score: 50 },
  {
    id: 'sample119',
    username: 'Kelsey Stone',
    accuracy: 88.8,
    total_score: 57,
  },
  { id: 'sample120', username: 'Logan Wheeler', accuracy: 76, total_score: 42 },
  {
    id: 'sample121',
    username: 'Alyssa Morgan',
    accuracy: 84.1,
    total_score: 51,
  },
  {
    id: 'sample122',
    username: 'Jordan Blake',
    accuracy: 90.0,
    total_score: 60,
  },
  {
    id: 'sample123',
    username: 'Chase Bennett',
    accuracy: 77.5,
    total_score: 43,
  },
  {
    id: 'sample124',
    username: 'Paige Hopkins',
    accuracy: 88.3,
    total_score: 57,
  },
  {
    id: 'sample125',
    username: 'Hunter Cross',
    accuracy: 81.2,
    total_score: 49,
  },
  {
    id: 'sample126',
    username: 'Autumn Riley',
    accuracy: 86.0,
    total_score: 54,
  },
  {
    id: 'sample127',
    username: 'Grant Bishop',
    accuracy: 92.7,
    total_score: 63,
  },
  {
    id: 'sample128',
    username: 'Brooke Curtis',
    accuracy: 79.6,
    total_score: 46,
  },
  { id: 'sample129', username: 'Spencer Fox', accuracy: 82.4, total_score: 50 },
  {
    id: 'sample130',
    username: 'Jade Armstrong',
    accuracy: 89.8,
    total_score: 59,
  },
  { id: 'sample131', username: 'Derek Lane', accuracy: 75.3, total_score: 40 },
  {
    id: 'sample132',
    username: 'Kaitlyn Shaw',
    accuracy: 87.9,
    total_score: 55,
  },
  {
    id: 'sample133',
    username: 'Colin Wheeler',
    accuracy: 80.7,
    total_score: 48,
  },
  {
    id: 'sample134',
    username: 'Maddie Holland',
    accuracy: 90.5,
    total_score: 61,
  },
  {
    id: 'sample135',
    username: 'Shane Barrett',
    accuracy: 78.2,
    total_score: 44,
  },
  {
    id: 'sample136',
    username: 'Jillian Page',
    accuracy: 85.6,
    total_score: 53,
  },
  {
    id: 'sample137',
    username: 'Travis Franklin',
    accuracy: 91.2,
    total_score: 62,
  },
  { id: 'sample138', username: 'Sydney Lowe', accuracy: 80.1, total_score: 47 },
  {
    id: 'sample139',
    username: 'Dawson Brewer',
    accuracy: 88.6,
    total_score: 58,
  },
  { id: 'sample140', username: 'Maya Harmon', accuracy: 76.8, total_score: 41 },
  {
    id: 'sample141',
    username: 'Parker Gibbs',
    accuracy: 83.9,
    total_score: 52,
  },
  {
    id: 'sample142',
    username: 'Sabrina Holt',
    accuracy: 89.3,
    total_score: 60,
  },
  { id: 'sample143', username: 'Miles Drake', accuracy: 78.7, total_score: 45 },
  {
    id: 'sample144',
    username: 'Cassidy Reese',
    accuracy: 86.5,
    total_score: 56,
  },
  {
    id: 'sample145',
    username: 'Evan Chandler',
    accuracy: 92.3,
    total_score: 64,
  },
  {
    id: 'sample146',
    username: 'Jocelyn Pratt',
    accuracy: 79.2,
    total_score: 47,
  },
  { id: 'sample147', username: 'Riley Tate', accuracy: 81.8, total_score: 51 },
  {
    id: 'sample148',
    username: 'Darren McCoy',
    accuracy: 88.9,
    total_score: 59,
  },
  {
    id: 'sample149',
    username: 'Chelsea Boone',
    accuracy: 75.7,
    total_score: 42,
  },
  {
    id: 'sample150',
    username: 'Brady Wilkins',
    accuracy: 87.1,
    total_score: 55,
  },
  {
    id: 'sample151',
    username: 'Mikayla Paul',
    accuracy: 80.3,
    total_score: 48,
  },
  { id: 'sample152', username: 'Reed Harmon', accuracy: 90.8, total_score: 62 },
  {
    id: 'sample153',
    username: 'Skylar Vaughn',
    accuracy: 78.4,
    total_score: 44,
  },
  {
    id: 'sample154',
    username: 'Tanner Reese',
    accuracy: 85.2,
    total_score: 53,
  },
  {
    id: 'sample155',
    username: 'Camille Barker',
    accuracy: 91.7,
    total_score: 63,
  },
  {
    id: 'sample156',
    username: 'Dustin Norris',
    accuracy: 80.9,
    total_score: 49,
  },
  {
    id: 'sample157',
    username: 'Mallory Steele',
    accuracy: 88.2,
    total_score: 58,
  },
  { id: 'sample158', username: 'Ryder Holt', accuracy: 76.1, total_score: 41 },
  { id: 'sample159', username: 'Jenna Banks', accuracy: 83.4, total_score: 52 },
  { id: 'sample160', username: 'Wesley Cain', accuracy: 89.5, total_score: 60 },
  { id: 'sample161', username: 'Aidan Pope', accuracy: 77.6, total_score: 43 },
  {
    id: 'sample162',
    username: 'Kara McBride',
    accuracy: 86.3,
    total_score: 55,
  },
  { id: 'sample163', username: 'Drew Conner', accuracy: 92.9, total_score: 64 },
  {
    id: 'sample164',
    username: 'Macy Shepherd',
    accuracy: 79.8,
    total_score: 47,
  },
  {
    id: 'sample165',
    username: 'Preston Todd',
    accuracy: 82.6,
    total_score: 50,
  },
  { id: 'sample166', username: 'Lila Newton', accuracy: 90.2, total_score: 61 },
  {
    id: 'sample167',
    username: 'Ruben McClain',
    accuracy: 78.9,
    total_score: 45,
  },
  {
    id: 'sample168',
    username: 'Kendall Hodge',
    accuracy: 85.8,
    total_score: 54,
  },
  { id: 'sample169', username: 'Trey Dorsey', accuracy: 91.4, total_score: 62 },
  {
    id: 'sample170',
    username: 'Michaela Boone',
    accuracy: 80.5,
    total_score: 48,
  },
  {
    id: 'sample171',
    username: 'Colby Phelps',
    accuracy: 88.7,
    total_score: 58,
  },
  {
    id: 'sample172',
    username: 'Arianna Glass',
    accuracy: 76.4,
    total_score: 41,
  },
  { id: 'sample173', username: 'Damon McGee', accuracy: 83.1, total_score: 51 },
  {
    id: 'sample174',
    username: 'Kylie Morrow',
    accuracy: 89.9,
    total_score: 60,
  },
  {
    id: 'sample175',
    username: 'Brendan Sellers',
    accuracy: 77.3,
    total_score: 44,
  },
  {
    id: 'sample176',
    username: 'Macy Harmon',
    accuracy: 86.6,
    total_score: 56,
  },
  { id: 'sample177', username: 'RileyTate_7', accuracy: 92.2, total_score: 63 },
  {
    id: 'sample178',
    username: 'Ninja',
    accuracy: 79.4,
    total_score: 47,
  },
  {
    id: 'sample179',
    username: 'Chelsea',
    accuracy: 81.9,
    total_score: 51,
  },
  {
    id: 'sample180',
    username: 'Brady Wilkins',
    accuracy: 88.8,
    total_score: 59,
  },
  {
    id: 'sample181',
    username: 'Godhandusa',
    accuracy: 75.5,
    total_score: 42,
  },
  {
    id: 'sample182',
    username: 'ReedyBeedy',
    accuracy: 87.2,
    total_score: 55,
  },
  {
    id: 'sample183',
    username: 'Ray Vaught',
    accuracy: 80.2,
    total_score: 48,
  },
  {
    id: 'sample184',
    username: 'Tanner Reese',
    accuracy: 90.7,
    total_score: 62,
  },
  {
    id: 'sample185',
    username: 'Camille Barker',
    accuracy: 78.1,
    total_score: 44,
  },
  {
    id: 'sample186',
    username: 'Dustin Norris',
    accuracy: 85.4,
    total_score: 53,
  },
  {
    id: 'sample187',
    username: 'Carson Jones',
    accuracy: 91.9,
    total_score: 63,
  },
  {
    id: 'sample188',
    username: 'RyderHolt_13',
    accuracy: 80.6,
    total_score: 49,
  },
  {
    id: 'sample189',
    username: 'JennaBanks_15',
    accuracy: 88.3,
    total_score: 58,
  },
  {
    id: 'sample190',
    username: 'WesleyCain_2',
    accuracy: 76.2,
    total_score: 41,
  },
  {
    id: 'sample191',
    username: 'Aidan Pope',
    accuracy: 83.7,
    total_score: 52,
  },
  {
    id: 'sample192',
    username: 'Kara McBride',
    accuracy: 89.6,
    total_score: 60,
  },
  {
    id: 'sample193',
    username: 'Drew Conner',
    accuracy: 77.8,
    total_score: 43,
  },
  {
    id: 'sample194',
    username: 'John Collins',
    accuracy: 86.1,
    total_score: 55,
  },
  {
    id: 'sample195',
    username: 'Cohn Jollins',
    accuracy: 92.8,
    total_score: 64,
  },
  {
    id: 'sample196',
    username: 'Stephen Curry',
    accuracy: 79.3,
    total_score: 47,
  },
  {
    id: 'sample197',
    username: 'Minecraft Rocks',
    accuracy: 82.5,
    total_score: 50,
  },
  {
    id: 'sample198',
    username: 'Jimmy Carter',
    accuracy: 90.3,
    total_score: 61,
  },
  {
    id: 'sample199',
    username: 'Vince Vincent',
    accuracy: 78.8,
    total_score: 45,
  },
  {
    id: 'sample200',
    username: 'Benson Boone',
    accuracy: 85.9,
    total_score: 54,
  },
  {
    id: 'sample201',
    username: 'Rihanna',
    accuracy: 91.5,
    total_score: 62,
  },
  {
    id: 'sample202',
    username: 'Ariana Grande',
    accuracy: 80.8,
    total_score: 48,
  },
  {
    id: 'sample203',
    username: 'Damon McGee',
    accuracy: 88.4,
    total_score: 58,
  },
  {
    id: 'sample204',
    username: 'Kylie Morrow',
    accuracy: 76.5,
    total_score: 41,
  },
  {
    id: 'sample205',
    username: 'Brendan$Sellers',
    accuracy: 83.2,
    total_score: 51,
  },
  {
    id: 'sample206',
    username: 'Alyssa Morgan',
    accuracy: 89.1,
    total_score: 60,
  },
  {
    id: 'sample207',
    username: 'Jordan Blake',
    accuracy: 77.4,
    total_score: 44,
  },
  {
    id: 'sample208',
    username: 'Chase Bennett',
    accuracy: 86.7,
    total_score: 56,
  },
  {
    id: 'sample209',
    username: 'Paige Hopkins',
    accuracy: 92.4,
    total_score: 63,
  },
  {
    id: 'sample210',
    username: 'Hunter Cross',
    accuracy: 79.5,
    total_score: 47,
  },
  {
    id: 'sample211',
    username: 'Autumn Riley',
    accuracy: 82.7,
    total_score: 50,
  },
  {
    id: 'sample212',
    username: 'Grant Bishop',
    accuracy: 90.9,
    total_score: 62,
  },
  {
    id: 'sample213',
    username: 'Quincy Thai',
    accuracy: 78.3,
    total_score: 44,
  },
  {
    id: 'sample214',
    username: 'SpencerFox_39',
    accuracy: 85.5,
    total_score: 53,
  },
  {
    id: 'sample215',
    username: 'Jade Armstrong',
    accuracy: 91.8,
    total_score: 63,
  },
  {
    id: 'sample216',
    username: 'Derek Lane',
    accuracy: 80.4,
    total_score: 49,
  },
  {
    id: 'sample217',
    username: 'Kaitlyn Shaw',
    accuracy: 88.5,
    total_score: 58,
  },
  {
    id: 'sample218',
    username: 'Colin Wheeler',
    accuracy: 76.6,
    total_score: 41,
  },
  {
    id: 'sample219',
    username: 'Maddie Holland',
    accuracy: 83.3,
    total_score: 52,
  },
  {
    id: 'sample220',
    username: 'Shane Barrett',
    accuracy: 89.7,
    total_score: 60,
  },
  {
    id: 'sample221',
    username: 'Jillian Page',
    accuracy: 77.9,
    total_score: 43,
  },
  {
    id: 'sample222',
    username: 'Travis Franklin',
    accuracy: 86.2,
    total_score: 55,
  },
  {
    id: 'sample223',
    username: 'Sydney Lowe',
    accuracy: 92.6,
    total_score: 64,
  },
  {
    id: 'sample224',
    username: 'Dawson Brewer',
    accuracy: 79.7,
    total_score: 47,
  },
  {
    id: 'sample225',
    username: 'Maya Harmon',
    accuracy: 82.9,
    total_score: 50,
  },
  {
    id: 'sample226',
    username: 'Parker Gibbs',
    accuracy: 90.4,
    total_score: 61,
  },
  {
    id: 'sample227',
    username: 'Sabrina Holt',
    accuracy: 78.5,
    total_score: 45,
  },
  {
    id: 'sample228',
    username: 'Miles.Drake',
    accuracy: 85.1,
    total_score: 54,
  },
  {
    id: 'sample229',
    username: 'CassidyReese ',
    accuracy: 91.3,
    total_score: 62,
  },
  {
    id: 'sample230',
    username: 'Evan Chandler',
    accuracy: 80.2,
    total_score: 48,
  },
  {
    id: 'sample231',
    username: 'Jocelyn Pratt',
    accuracy: 88.9,
    total_score: 58,
  },
  {
    id: 'sample232',
    username: 'Drake',
    accuracy: 76.7,
    total_score: 41,
  },
  {
    id: 'sample233',
    username: 'Darren McCoy',
    accuracy: 83.5,
    total_score: 51,
  },
  {
    id: 'sample234',
    username: 'Chelsea Boone',
    accuracy: 89.2,
    total_score: 60,
  },
  {
    id: 'sample235',
    username: 'Akira Takahashi',
    accuracy: 87.2,
    total_score: 44,
  },
  { id: 'sample236', username: 'Priya Desai', accuracy: 92.1, total_score: 53 },
  {
    id: 'sample237',
    username: 'Kwame Mensah',
    accuracy: 78.5,
    total_score: 39,
  },
  {
    id: 'sample238',
    username: 'Fatou Ndiaye',
    accuracy: 85.6,
    total_score: 51,
  },
  {
    id: 'sample239',
    username: 'Lars Johansen',
    accuracy: 90.3,
    total_score: 62,
  },
  {
    id: 'sample240',
    username: 'Svetlana Petrova',
    accuracy: 81.7,
    total_score: 47,
  },
  { id: 'sample241', username: 'Mei Lin', accuracy: 88.9, total_score: 55 },
  {
    id: 'sample242',
    username: 'Carlos Mendez',
    accuracy: 76.4,
    total_score: 41,
  },
  {
    id: 'sample243',
    username: 'Leila Benali',
    accuracy: 83.2,
    total_score: 49,
  },
  { id: 'sample244', username: 'Omar Farouk', accuracy: 91.5, total_score: 60 },
  { id: 'sample245', username: 'Sofia Rossi', accuracy: 79.8, total_score: 43 },
  { id: 'sample246', username: 'Jin Park', accuracy: 86.1, total_score: 52 },
  { id: 'sample247', username: 'Amina Yusuf', accuracy: 93.4, total_score: 64 },
  {
    id: 'sample248',
    username: 'Lucas Moreira',
    accuracy: 80.6,
    total_score: 46,
  },
  { id: 'sample249', username: 'Nia Okafor', accuracy: 89.7, total_score: 56 },
  { id: 'sample250', username: 'Yara Haddad', accuracy: 77.3, total_score: 40 },
  { id: 'sample251', username: 'Ravi Patel', accuracy: 84.5, total_score: 50 },
  {
    id: 'sample252',
    username: 'Elena Popescu',
    accuracy: 90.9,
    total_score: 61,
  },
  {
    id: 'sample253',
    username: 'Samir Al-Farsi',
    accuracy: 82.4,
    total_score: 48,
  },
  { id: 'sample254', username: 'Maya Cohen', accuracy: 88.2, total_score: 54 },
  { id: 'sample255', username: 'Nguyen Van', accuracy: 75.9, total_score: 38 },
  {
    id: 'sample256',
    username: 'Zanele Dlamini',
    accuracy: 87.6,
    total_score: 45,
  },
  {
    id: 'sample257',
    username: 'Hiroshi Sato',
    accuracy: 92.8,
    total_score: 63,
  },
  {
    id: 'sample258',
    username: 'Isabella Costa',
    accuracy: 80.2,
    total_score: 42,
  },
  {
    id: 'sample259',
    username: 'Mohammed Saleh',
    accuracy: 85.3,
    total_score: 51,
  },
  {
    id: 'sample260',
    username: 'Chinonso Eze',
    accuracy: 91.1,
    total_score: 59,
  },
  {
    id: 'sample261',
    username: 'Anastasia Ivanova',
    accuracy: 78.7,
    total_score: 44,
  },
  {
    id: 'sample262',
    username: 'Pedro Alvarez',
    accuracy: 83.9,
    total_score: 50,
  },
  { id: 'sample263', username: 'Siti Rahman', accuracy: 89.4, total_score: 57 },
  {
    id: 'sample264',
    username: 'Mikhail Orlov',
    accuracy: 76.8,
    total_score: 41,
  },
  { id: 'sample265', username: 'Aisha Abdi', accuracy: 84.7, total_score: 49 },
  {
    id: 'sample266',
    username: 'Giulia Bianchi',
    accuracy: 90.5,
    total_score: 62,
  },
  {
    id: 'sample267',
    username: 'Rajesh Kumar',
    accuracy: 81.3,
    total_score: 47,
  },
  {
    id: 'sample268',
    username: 'Fatima Zahra',
    accuracy: 87.8,
    total_score: 55,
  },
  {
    id: 'sample269',
    username: 'Tariq Mahmoud',
    accuracy: 93.2,
    total_score: 65,
  },
  { id: 'sample270', username: 'Linh Tran', accuracy: 79.5, total_score: 43 },
  {
    id: 'sample271',
    username: 'Sibongile Ndlovu',
    accuracy: 86.4,
    total_score: 52,
  },
  {
    id: 'sample272',
    username: 'Diego Fernandez',
    accuracy: 92.3,
    total_score: 63,
  },
  { id: 'sample273', username: 'Mina Khalil', accuracy: 80.8, total_score: 46 },
  {
    id: 'sample274',
    username: 'Yusuf Hassan',
    accuracy: 89.1,
    total_score: 56,
  },
  {
    id: 'sample275',
    username: 'Sakura Yamamoto',
    accuracy: 77.6,
    total_score: 40,
  },
  {
    id: 'sample276',
    username: 'Gabriel Souza',
    accuracy: 84.3,
    total_score: 50,
  },
  {
    id: 'sample277',
    username: 'Nadia El-Sayed',
    accuracy: 90.7,
    total_score: 61,
  },
  {
    id: 'sample278',
    username: 'Kwesi Boateng',
    accuracy: 82.1,
    total_score: 48,
  },
  { id: 'sample279', username: 'Maria Silva', accuracy: 88.5, total_score: 54 },
  { id: 'sample280', username: 'Wei Zhang', accuracy: 75.2, total_score: 37 },
  {
    id: 'sample281',
    username: 'Soraya Benitez',
    accuracy: 87.4,
    total_score: 45,
  },
  {
    id: 'sample282',
    username: 'Jamal Carter',
    accuracy: 92.6,
    total_score: 63,
  },
  { id: 'sample283', username: 'Amira Said', accuracy: 80.4, total_score: 42 },
  {
    id: 'sample284',
    username: 'Leandro Pereira',
    accuracy: 85.1,
    total_score: 51,
  },
  {
    id: 'sample285',
    username: 'Sawsan Barakat',
    accuracy: 91.3,
    total_score: 59,
  },
  {
    id: 'sample286',
    username: 'Dmitry Volkov',
    accuracy: 78.9,
    total_score: 44,
  },
  { id: 'sample287', username: 'Ava Kim', accuracy: 83.6, total_score: 50 },
  {
    id: 'sample288',
    username: 'Oluwaseun Adeyemi',
    accuracy: 89.9,
    total_score: 57,
  },
  { id: 'sample289', username: 'Hanae Mori', accuracy: 76.1, total_score: 41 },
  {
    id: 'sample290',
    username: 'Rashid Al-Mansoori',
    accuracy: 84.9,
    total_score: 49,
  },
  {
    id: 'sample291',
    username: 'Sofia Papadopoulos',
    accuracy: 90.1,
    total_score: 62,
  },
  { id: 'sample292', username: 'Arjun Singh', accuracy: 81.5, total_score: 47 },
  {
    id: 'sample293',
    username: 'Samira Farah',
    accuracy: 87.1,
    total_score: 55,
  },
  {
    id: 'sample294',
    username: 'Mateo Gutierrez',
    accuracy: 93.7,
    total_score: 65,
  },
  {
    id: 'sample295',
    username: 'Trang Nguyen',
    accuracy: 79.2,
    total_score: 43,
  },
  {
    id: 'sample296',
    username: 'Gas',
    accuracy: 86.7,
    total_score: 52,
  },
  {
    id: 'sample297',
    username: 'Luisa Romero',
    accuracy: 92.5,
    total_score: 63,
  },
  { id: 'sample298', username: 'Omar Sharif', accuracy: 80.9, total_score: 46 },
  {
    id: 'sample299',
    username: 'Layla Hussein',
    accuracy: 89.3,
    total_score: 56,
  },
  {
    id: 'sample300',
    username: 'Yuki Nakamura',
    accuracy: 77.8,
    total_score: 40,
  },
  {
    id: 'sample301',
    username: 'Thiago Almeida',
    accuracy: 84.2,
    total_score: 50,
  },
  {
    id: 'sample302',
    username: 'Mariam Diallo',
    accuracy: 90.8,
    total_score: 61,
  },
  {
    id: 'sample303',
    username: 'Nikhil Sharma',
    accuracy: 82.3,
    total_score: 48,
  },
  {
    id: 'sample304',
    username: 'Aisha Mohamed',
    accuracy: 88.7,
    total_score: 54,
  },
  {
    id: 'sample305',
    username: 'Jorge Castillo',
    accuracy: 75.5,
    total_score: 38,
  },
  {
    id: 'sample306',
    username: 'Zahra Rahimi',
    accuracy: 87.9,
    total_score: 45,
  },
  { id: 'sample307', username: 'Ivan Petrov', accuracy: 92.2, total_score: 63 },
  {
    id: 'sample308',
    username: 'Siti Nurhaliza',
    accuracy: 80.3,
    total_score: 42,
  },
  {
    id: 'sample309',
    username: 'Mohamed Elamin',
    accuracy: 85.4,
    total_score: 51,
  },
  {
    id: 'sample310',
    username: 'Chinedu Okeke',
    accuracy: 91.7,
    total_score: 59,
  },
  {
    id: 'sample311',
    username: 'Anya Kuznetsova',
    accuracy: 78.6,
    total_score: 44,
  },
  {
    id: 'sample312',
    username: 'Pedro Santos',
    accuracy: 83.8,
    total_score: 50,
  },
  {
    id: 'sample313',
    username: 'Nour Fakhoury',
    accuracy: 89.6,
    total_score: 57,
  },
  {
    id: 'sample314',
    username: 'Mikhail Ivanov',
    accuracy: 76.9,
    total_score: 41,
  },
  {
    id: 'sample315',
    username: 'Amina Diallo',
    accuracy: 84.6,
    total_score: 49,
  },
  {
    id: 'sample316',
    username: 'Giovanni Romano',
    accuracy: 90.4,
    total_score: 62,
  },
  {
    id: 'sample317',
    username: 'Priyanka Mehra',
    accuracy: 81.1,
    total_score: 47,
  },
  { id: 'sample318', username: 'Fatima Noor', accuracy: 87.3, total_score: 55 },
  {
    id: 'sample319',
    username: 'Tarek El-Sayed',
    accuracy: 93.1,
    total_score: 65,
  },
  { id: 'sample320', username: 'Linh Pham', accuracy: 79.7, total_score: 43 },
  {
    id: 'sample321',
    username: 'Sipho Mthembu',
    accuracy: 86.2,
    total_score: 52,
  },
  {
    id: 'sample322',
    username: 'Diego Morales',
    accuracy: 92.9,
    total_score: 63,
  },
  {
    id: 'sample323',
    username: 'Mina Youssef',
    accuracy: 80.7,
    total_score: 46,
  },
  { id: 'sample324', username: 'Yusuf Ali', accuracy: 89.2, total_score: 56 },
  {
    id: 'sample325',
    username: 'Sakura Fujimoto',
    accuracy: 77.5,
    total_score: 40,
  },
  {
    id: 'sample326',
    username: 'Gabriela Souza',
    accuracy: 84.8,
    total_score: 50,
  },
  { id: 'sample327', username: 'Nadia Karim', accuracy: 90.6, total_score: 61 },
  { id: 'sample328', username: 'Kwame Osei', accuracy: 82.5, total_score: 48 },
  {
    id: 'sample329',
    username: 'Maria Torres',
    accuracy: 88.1,
    total_score: 54,
  },
  { id: 'sample330', username: 'Wei Liu', accuracy: 75.7, total_score: 38 },
  {
    id: 'sample331',
    username: 'Soraya Lopez',
    accuracy: 87.5,
    total_score: 45,
  },
  { id: 'sample332', username: 'Jamal Brown', accuracy: 92.4, total_score: 63 },
  {
    id: 'sample333',
    username: 'Amira Khaled',
    accuracy: 80.5,
    total_score: 42,
  },
  {
    id: 'sample334',
    username: 'Leandro Costa',
    accuracy: 85.2,
    total_score: 51,
  },
  {
    id: 'sample335',
    username: 'Sawsan Khalil',
    accuracy: 91.6,
    total_score: 59,
  },
  {
    id: 'sample336',
    username: 'Dmitry Sokolov',
    accuracy: 78.8,
    total_score: 44,
  },
  { id: 'sample337', username: 'Ava Lee', accuracy: 83.7, total_score: 50 },
  {
    id: 'sample338',
    username: 'Oluwatosin Adebayo',
    accuracy: 89.8,
    total_score: 57,
  },
  {
    id: 'sample339',
    username: 'Hanae Suzuki',
    accuracy: 76.2,
    total_score: 41,
  },
  {
    id: 'sample340',
    username: 'Rashid Al-Hassan',
    accuracy: 84.4,
    total_score: 49,
  },
  {
    id: 'sample341',
    username: 'Sofia Georgiou',
    accuracy: 90.2,
    total_score: 62,
  },
  { id: 'sample342', username: 'Arjun Nair', accuracy: 81.4, total_score: 47 },
  {
    id: 'sample343',
    username: 'Samira Ahmed',
    accuracy: 87.7,
    total_score: 55,
  },
  { id: 'sample344', username: 'Mateo Rojas', accuracy: 93.3, total_score: 65 },
  { id: 'sample345', username: 'Trang Le', accuracy: 79.4, total_score: 43 },
  { id: 'sample346', username: 'GoDubz', accuracy: 86.5, total_score: 52 },
  {
    id: 'sample347',
    username: 'Luisa Fernandez',
    accuracy: 92.7,
    total_score: 63,
  },
  {
    id: 'sample348',
    username: 'Omar Khalifa',
    accuracy: 80.1,
    total_score: 46,
  },
  {
    id: 'sample349',
    username: 'Layla Ibrahim',
    accuracy: 89.5,
    total_score: 56,
  },
  {
    id: 'sample350',
    username: 'Yuki Kobayashi',
    accuracy: 77.9,
    total_score: 40,
  },
  {
    id: 'sample351',
    username: 'Thiago Barbosa',
    accuracy: 84.3,
    total_score: 50,
  },
  {
    id: 'sample352',
    username: 'Mariam Hassan',
    accuracy: 90.7,
    total_score: 61,
  },
  {
    id: 'sample353',
    username: 'Nikhil Patel',
    accuracy: 82.2,
    total_score: 48,
  },
  { id: 'sample354', username: 'Aisha Ali', accuracy: 88.6, total_score: 54 },
  {
    id: 'sample355',
    username: 'Jorge Ramirez',
    accuracy: 75.4,
    total_score: 38,
  },
  { id: 'sample356', username: 'Zahra Alavi', accuracy: 87.2, total_score: 45 },
  {
    id: 'sample357',
    username: 'Ivan Smirnov',
    accuracy: 92.1,
    total_score: 63,
  },
  { id: 'sample358', username: 'Siti Zainab', accuracy: 80.2, total_score: 42 },
  {
    id: 'sample359',
    username: 'Mohamed Hassan',
    accuracy: 85.5,
    total_score: 51,
  },
  {
    id: 'sample360',
    username: 'Chinedu Nwosu',
    accuracy: 91.8,
    total_score: 59,
  },
  {
    id: 'sample361',
    username: 'Anya Morozova',
    accuracy: 78.3,
    total_score: 44,
  },
  { id: 'sample362', username: 'Pedro Lima', accuracy: 83.5, total_score: 50 },
  {
    id: 'sample363',
    username: 'Nour El-Tayeb',
    accuracy: 89.9,
    total_score: 57,
  },
  {
    id: 'sample364',
    username: 'Mikhail Popov',
    accuracy: 76.6,
    total_score: 41,
  },
  { id: 'sample365', username: 'Amina Ahmed', accuracy: 84.1, total_score: 49 },
  {
    id: 'sample366',
    username: 'Giovanni Greco',
    accuracy: 90.3,
    total_score: 62,
  },
  {
    id: 'sample367',
    username: 'Priyanka Singh',
    accuracy: 81.6,
    total_score: 47,
  },
  { id: 'sample368', username: 'Fatima Khan', accuracy: 87.5, total_score: 55 },
  {
    id: 'sample369',
    username: 'Tarek Hassan',
    accuracy: 93.4,
    total_score: 65,
  },
  { id: 'sample370', username: 'Linh Hoang', accuracy: 79.1, total_score: 43 },
  { id: 'sample371', username: 'Siphofds', accuracy: 86.8, total_score: 52 },
  {
    id: 'sample372',
    username: 'Diego Vargas',
    accuracy: 92.6,
    total_score: 63,
  },
  { id: 'sample373', username: 'Mina Saleh', accuracy: 80.6, total_score: 46 },
  {
    id: 'sample374',
    username: 'Yusuf Mohamed',
    accuracy: 89.7,
    total_score: 56,
  },
  {
    id: 'sample375',
    username: 'Sakura Tanaka',
    accuracy: 77.2,
    total_score: 40,
  },
  {
    id: 'sample376',
    username: 'Gabriel Lima',
    accuracy: 84.7,
    total_score: 50,
  },
  {
    id: 'sample377',
    username: 'Nadia Hassan',
    accuracy: 90.9,
    total_score: 61,
  },
  {
    id: 'sample378',
    username: 'Kwame Appiah',
    accuracy: 82.4,
    total_score: 48,
  },
  {
    id: 'sample379',
    username: 'Maria Gonzalez',
    accuracy: 88.2,
    total_score: 54,
  },
  { id: 'sample380', username: 'Wei Chen', accuracy: 75.9, total_score: 38 },
  {
    id: 'sample381',
    username: 'Soraya Ahmed',
    accuracy: 87.6,
    total_score: 45,
  },
  { id: 'sample382', username: 'Jamal White', accuracy: 92.8, total_score: 63 },
  { id: 'sample383', username: 'Amira Ali', accuracy: 80.2, total_score: 42 },
  {
    id: 'sample384',
    username: 'Leandro Silva',
    accuracy: 85.3,
    total_score: 51,
  },
  {
    id: 'sample385',
    username: 'Sawsan Khaled',
    accuracy: 91.1,
    total_score: 59,
  },
  {
    id: 'sample386',
    username: 'Dmitry Ivanov',
    accuracy: 78.7,
    total_score: 44,
  },
  { id: 'sample387', username: 'Ava Wang', accuracy: 83.9, total_score: 50 },
  {
    id: 'sample388',
    username: 'Oluwaseun Okafor',
    accuracy: 89.4,
    total_score: 57,
  },
  {
    id: 'sample389',
    username: 'Hanae Takagi',
    accuracy: 76.8,
    total_score: 41,
  },
  {
    id: 'sample390',
    username: 'Rashid Al-Farsi',
    accuracy: 84.7,
    total_score: 49,
  },
  { id: 'sample391', username: 'Sofia Costa', accuracy: 90.5, total_score: 62 },
  { id: 'sample392', username: 'Arjun Patel', accuracy: 81.3, total_score: 47 },
  { id: 'sample393', username: 'Samira Noor', accuracy: 87.8, total_score: 55 },
  {
    id: 'sample394',
    username: 'Mateo Alvarez',
    accuracy: 93.2,
    total_score: 65,
  },
  { id: 'sample395', username: 'Trang Tran', accuracy: 79.5, total_score: 43 },
  { id: 'sample396', username: 'Sipho Zulu', accuracy: 86.4, total_score: 52 },
  {
    id: 'sample397',
    username: 'Luisa Martinez',
    accuracy: 92.3,
    total_score: 63,
  },
  { id: 'sample398', username: 'Omar Hassan', accuracy: 80.8, total_score: 46 },
  {
    id: 'sample399',
    username: 'Layla Khalil',
    accuracy: 89.1,
    total_score: 56,
  },
  {
    id: 'sample400',
    username: 'Yuki Sakamoto',
    accuracy: 77.6,
    total_score: 40,
  },
  {
    id: 'sample401',
    username: 'Leandro Batista',
    accuracy: 85.2,
    total_score: 51,
  },
  { id: 'sample402', username: 'Minh Chau', accuracy: 90.1, total_score: 62 },
  {
    id: 'sample403',
    username: 'Aaliyah Hassan',
    accuracy: 78.7,
    total_score: 44,
  },
  {
    id: 'sample404',
    username: 'Santiago Rivera',
    accuracy: 87.5,
    total_score: 53,
  },
  {
    id: 'sample405',
    username: 'Yasmine Elbaz',
    accuracy: 92.3,
    total_score: 64,
  },
  {
    id: 'sample406',
    username: 'Tenzin Dorji',
    accuracy: 80.6,
    total_score: 46,
  },
  {
    id: 'sample407',
    username: 'Helena Schmidt',
    accuracy: 88.9,
    total_score: 55,
  },
  {
    id: 'sample408',
    username: 'Rohan Kapoor',
    accuracy: 76.4,
    total_score: 41,
  },
  {
    id: 'sample409',
    username: 'Mariam Gerges',
    accuracy: 83.2,
    total_score: 49,
  },
  {
    id: 'sample410',
    username: 'ajkl3a',
    accuracy: 91.5,
    total_score: 60,
  },
  { id: 'sample411', username: 'Fatima Sy', accuracy: 79.8, total_score: 43 },
  {
    id: 'sample412',
    username: 'Dae-Hyun Kim',
    accuracy: 86.1,
    total_score: 52,
  },
  { id: 'sample413', username: 'Lina Haddad', accuracy: 93.4, total_score: 64 },
  { id: 'sample414', username: 'Pedro Costa', accuracy: 80.9, total_score: 46 },
  {
    id: 'sample415',
    username: 'Ava Robinson',
    accuracy: 89.7,
    total_score: 56,
  },
  { id: 'sample416', username: 'Zubair Khan', accuracy: 77.3, total_score: 40 },
  {
    id: 'sample417',
    username: 'Sofia Alvarez',
    accuracy: 84.5,
    total_score: 50,
  },
  {
    id: 'sample418',
    username: 'Niko Petrovic',
    accuracy: 90.9,
    total_score: 61,
  },
  { id: 'sample419', username: 'Maya Singh', accuracy: 82.4, total_score: 48 },
  { id: 'sample420', username: 'Jin Woo', accuracy: 88.2, total_score: 54 },
  { id: 'sample421', username: 'Luca Romano', accuracy: 75.9, total_score: 38 },
  { id: 'sample422', username: 'Aisha Bello', accuracy: 87.6, total_score: 45 },
  { id: 'sample423', username: 'Yusuf Musa', accuracy: 92.8, total_score: 63 },
  { id: 'sample424', username: 'Siti Aminah', accuracy: 80.2, total_score: 42 },
  {
    id: 'sample425',
    username: 'Omar Suleiman',
    accuracy: 85.3,
    total_score: 51,
  },
  {
    id: 'sample426',
    username: 'Elena Ivanova',
    accuracy: 91.1,
    total_score: 59,
  },
  {
    id: 'sample427',
    username: 'Kwame Boateng',
    accuracy: 78.7,
    total_score: 44,
  },
  {
    id: 'sample428',
    username: 'Isabella Moretti',
    accuracy: 83.9,
    total_score: 50,
  },
  {
    id: 'sample429',
    username: 'Nour Elmasry',
    accuracy: 89.4,
    total_score: 57,
  },
  { id: 'sample430', username: 'Wei Sun', accuracy: 76.8, total_score: 41 },
  {
    id: 'sample431',
    username: 'Soraya Rahimi',
    accuracy: 84.7,
    total_score: 49,
  },
  {
    id: 'sample432',
    username: 'Gabriel Lima',
    accuracy: 90.5,
    total_score: 62,
  },
  {
    id: 'sample433',
    username: 'Priya Sharma',
    accuracy: 81.3,
    total_score: 47,
  },
  {
    id: 'sample434',
    username: 'Fatoumata Diallo',
    accuracy: 87.8,
    total_score: 55,
  },
  { id: 'sample435', username: 'Tariq Aziz', accuracy: 93.2, total_score: 65 },
  { id: 'sample436', username: 'Linh Nguyen', accuracy: 79.5, total_score: 43 },
  { id: 'sample437', username: 'Moyooo', accuracy: 86.4, total_score: 52 },
  {
    id: 'sample438',
    username: 'Diego Castillo',
    accuracy: 92.3,
    total_score: 63,
  },
  { id: 'sample439', username: 'Mina Farouk', accuracy: 80.8, total_score: 46 },
  {
    id: 'sample440',
    username: 'Yusuf Ibrahim',
    accuracy: 89.1,
    total_score: 56,
  },
  {
    id: 'sample441',
    username: 'Sakura Watanabe',
    accuracy: 77.6,
    total_score: 40,
  },
  {
    id: 'sample442',
    username: 'Gabriela Torres',
    accuracy: 84.3,
    total_score: 50,
  },
  {
    id: 'sample443',
    username: 'Nadia Benali',
    accuracy: 90.7,
    total_score: 61,
  },
  {
    id: 'sample444',
    username: 'Kwesi Mensah',
    accuracy: 82.1,
    total_score: 48,
  },
  { id: 'sample445', username: 'Maria Sousa', accuracy: 88.5, total_score: 54 },
  { id: 'sample446', username: 'Wei Chen', accuracy: 75.2, total_score: 37 },
  {
    id: 'sample447',
    username: 'Soraya Lopez',
    accuracy: 87.4,
    total_score: 45,
  },
  { id: 'sample448', username: 'Jamal Ahmed', accuracy: 92.6, total_score: 63 },
  {
    id: 'sample449',
    username: 'Amira Khalil',
    accuracy: 80.4,
    total_score: 42,
  },
  {
    id: 'sample450',
    username: 'Leandro Pereira',
    accuracy: 85.1,
    total_score: 51,
  },
  {
    id: 'sample451',
    username: 'Sawsan Barakat',
    accuracy: 91.3,
    total_score: 59,
  },
  {
    id: 'sample452',
    username: 'Dmitry Volkov',
    accuracy: 78.9,
    total_score: 44,
  },
  { id: 'sample453', username: 'Ava Kim', accuracy: 83.6, total_score: 50 },
  {
    id: 'sample454',
    username: 'Oluwaseun Adeyemi',
    accuracy: 89.9,
    total_score: 57,
  },
  { id: 'sample455', username: 'Hanae Mori', accuracy: 76.1, total_score: 41 },
  {
    id: 'sample456',
    username: 'Rashid Al-Mansoori',
    accuracy: 84.9,
    total_score: 49,
  },
  {
    id: 'sample457',
    username: 'Sofia Papadopoulos',
    accuracy: 90.1,
    total_score: 62,
  },
  { id: 'sample458', username: 'Arjun Singh', accuracy: 81.5, total_score: 47 },
  {
    id: 'sample459',
    username: 'Samira Farah',
    accuracy: 87.1,
    total_score: 55,
  },
  {
    id: 'sample460',
    username: 'Mateo Gutierrez',
    accuracy: 93.7,
    total_score: 65,
  },
  {
    id: 'sample461',
    username: 'Trang Nguyen',
    accuracy: 79.2,
    total_score: 43,
  },
  {
    id: 'sample462',
    username: 'JohnnySins',
    accuracy: 86.7,
    total_score: 52,
  },
  {
    id: 'sample463',
    username: 'Luisa Romero',
    accuracy: 92.5,
    total_score: 63,
  },
  { id: 'sample464', username: 'Omar Sharif', accuracy: 80.9, total_score: 46 },
  {
    id: 'sample465',
    username: 'Layla Hussein',
    accuracy: 89.3,
    total_score: 56,
  },
  {
    id: 'sample466',
    username: 'Yuki Nakamura',
    accuracy: 77.8,
    total_score: 40,
  },
  {
    id: 'sample467',
    username: 'Thiago Almeida',
    accuracy: 84.2,
    total_score: 50,
  },
  {
    id: 'sample468',
    username: 'Mariam Diallo',
    accuracy: 90.8,
    total_score: 61,
  },
  {
    id: 'sample469',
    username: 'Nikhil Sharma',
    accuracy: 82.3,
    total_score: 48,
  },
  {
    id: 'sample470',
    username: 'Aisha Mohamed',
    accuracy: 88.7,
    total_score: 54,
  },
  {
    id: 'sample471',
    username: 'Jorge Castillo',
    accuracy: 75.5,
    total_score: 38,
  },
  {
    id: 'sample472',
    username: 'Zahra Rahimi',
    accuracy: 87.9,
    total_score: 45,
  },
  { id: 'sample473', username: 'Ivan Petrov', accuracy: 92.2, total_score: 63 },
  {
    id: 'sample474',
    username: 'Siti Nurhaliza',
    accuracy: 80.3,
    total_score: 42,
  },
  {
    id: 'sample475',
    username: 'Mohamed Elamin',
    accuracy: 85.4,
    total_score: 51,
  },
  {
    id: 'sample476',
    username: 'Chinedu Okeke',
    accuracy: 91.7,
    total_score: 59,
  },
  {
    id: 'sample477',
    username: 'Anya Kuznetsova',
    accuracy: 78.6,
    total_score: 44,
  },
  {
    id: 'sample478',
    username: 'Pedro Santos',
    accuracy: 83.8,
    total_score: 50,
  },
  {
    id: 'sample479',
    username: 'Nour Fakhoury',
    accuracy: 89.6,
    total_score: 57,
  },
  {
    id: 'sample480',
    username: 'Mikhail Ivanov',
    accuracy: 76.9,
    total_score: 41,
  },
  {
    id: 'sample481',
    username: 'Amina Diallo',
    accuracy: 84.6,
    total_score: 49,
  },
  {
    id: 'sample482',
    username: 'Giovanni Romano',
    accuracy: 90.4,
    total_score: 62,
  },
  {
    id: 'sample483',
    username: 'Priyanka Mehra',
    accuracy: 81.1,
    total_score: 47,
  },
  { id: 'sample484', username: 'Fatima Noor', accuracy: 87.3, total_score: 55 },
  {
    id: 'sample485',
    username: 'Tarek El-Sayed',
    accuracy: 93.1,
    total_score: 65,
  },
  { id: 'sample486', username: 'Linh Pham', accuracy: 79.7, total_score: 43 },
  {
    id: 'sample487',
    username: 'Onyeka320',
    accuracy: 86.2,
    total_score: 52,
  },
  {
    id: 'sample488',
    username: 'Diego Morales',
    accuracy: 92.9,
    total_score: 63,
  },
  {
    id: 'sample489',
    username: 'Mina Youssef',
    accuracy: 80.7,
    total_score: 46,
  },
  { id: 'sample490', username: 'Yusuf Ali', accuracy: 89.2, total_score: 56 },
  {
    id: 'sample491',
    username: 'Sakura Fujimoto',
    accuracy: 77.5,
    total_score: 40,
  },
  {
    id: 'sample492',
    username: 'Gabriela Souza',
    accuracy: 84.8,
    total_score: 50,
  },
  { id: 'sample493', username: 'Nadia Karim', accuracy: 90.6, total_score: 61 },
  { id: 'sample494', username: 'Kwame Osei', accuracy: 82.5, total_score: 48 },
  {
    id: 'sample495',
    username: 'Maria Torres',
    accuracy: 88.1,
    total_score: 54,
  },
  { id: 'sample496', username: 'Wei Liu', accuracy: 75.7, total_score: 38 },
  {
    id: 'sample497',
    username: 'Soraya Lopez',
    accuracy: 87.5,
    total_score: 45,
  },
  { id: 'sample498', username: 'Jamal Brown', accuracy: 92.4, total_score: 63 },
  {
    id: 'sample499',
    username: 'Amira Khaled',
    accuracy: 80.5,
    total_score: 42,
  },
  {
    id: 'sample500',
    username: 'Leandro Costa',
    accuracy: 85.2,
    total_score: 51,
  },
  {
    id: 'sample501',
    username: 'Sawsan Khalil',
    accuracy: 91.6,
    total_score: 59,
  },
  {
    id: 'sample502',
    username: 'Dmitry Sokolov',
    accuracy: 78.8,
    total_score: 44,
  },
  { id: 'sample503', username: 'Ava Lee', accuracy: 83.7, total_score: 50 },
  {
    id: 'sample504',
    username: 'Oluwatosin Adebayo',
    accuracy: 89.8,
    total_score: 57,
  },
  {
    id: 'sample505',
    username: 'Hanae Suzuki',
    accuracy: 76.2,
    total_score: 41,
  },
  {
    id: 'sample506',
    username: 'Rashid Al-Hassan',
    accuracy: 84.4,
    total_score: 49,
  },
  {
    id: 'sample507',
    username: 'Sofia Georgiou',
    accuracy: 90.2,
    total_score: 62,
  },
  { id: 'sample508', username: 'Arjun Nair', accuracy: 81.4, total_score: 47 },
  {
    id: 'sample509',
    username: 'Samira Ahmed',
    accuracy: 87.7,
    total_score: 55,
  },
  { id: 'sample510', username: 'Mateo Rojas', accuracy: 93.3, total_score: 65 },
  { id: 'sample511', username: 'Trang Le', accuracy: 79.4, total_score: 43 },
  { id: 'sample512', username: 'IloveTPayne', accuracy: 86.5, total_score: 52 },
  {
    id: 'sample513',
    username: 'Luisa Fernandez',
    accuracy: 92.7,
    total_score: 63,
  },
  {
    id: 'sample514',
    username: 'Omar Khalifa',
    accuracy: 80.1,
    total_score: 46,
  },
  {
    id: 'sample515',
    username: 'Layla Ibrahim',
    accuracy: 89.5,
    total_score: 56,
  },
  {
    id: 'sample516',
    username: 'Yuki Kobayashi',
    accuracy: 77.9,
    total_score: 40,
  },
  {
    id: 'sample517',
    username: 'Thiago Barbosa',
    accuracy: 84.3,
    total_score: 50,
  },
  {
    id: 'sample518',
    username: 'Mariam Hassan',
    accuracy: 90.7,
    total_score: 61,
  },
  {
    id: 'sample519',
    username: 'Nikhil Patel',
    accuracy: 82.2,
    total_score: 48,
  },
  { id: 'sample520', username: 'Aisha Ali', accuracy: 88.6, total_score: 54 },
  {
    id: 'sample521',
    username: 'Jorge Ramirez',
    accuracy: 75.4,
    total_score: 38,
  },
  { id: 'sample522', username: 'Zahra Alavi', accuracy: 87.2, total_score: 45 },
  {
    id: 'sample523',
    username: 'Ivan Smirnov',
    accuracy: 92.1,
    total_score: 63,
  },
  { id: 'sample524', username: 'Siti Zainab', accuracy: 80.2, total_score: 42 },
  {
    id: 'sample525',
    username: 'Mohamed Hassan',
    accuracy: 85.5,
    total_score: 51,
  },
  {
    id: 'sample526',
    username: 'Chinedu Nwosu',
    accuracy: 91.8,
    total_score: 59,
  },
  {
    id: 'sample527',
    username: 'Anya Morozova',
    accuracy: 78.3,
    total_score: 44,
  },
  { id: 'sample528', username: 'Pedro Lima', accuracy: 83.5, total_score: 50 },
  {
    id: 'sample529',
    username: 'Nour El-Tayeb',
    accuracy: 89.9,
    total_score: 57,
  },
  {
    id: 'sample530',
    username: 'Mikhail Popov',
    accuracy: 76.6,
    total_score: 41,
  },
  { id: 'sample531', username: 'Amina Ahmed', accuracy: 84.1, total_score: 49 },
  {
    id: 'sample532',
    username: 'Giovanni Greco',
    accuracy: 90.3,
    total_score: 62,
  },
  {
    id: 'sample533',
    username: 'Priyanka Singh',
    accuracy: 81.6,
    total_score: 47,
  },
  { id: 'sample534', username: 'Fatima Khan', accuracy: 87.5, total_score: 55 },
  {
    id: 'sample535',
    username: 'Tarek Hassan',
    accuracy: 93.4,
    total_score: 65,
  },
  { id: 'sample536', username: 'Linh Hoang', accuracy: 79.1, total_score: 43 },
  { id: 'sample537', username: 'Trae._.Jones', accuracy: 86.8, total_score: 52 },
  {
    id: 'sample538',
    username: 'Diego Vargas',
    accuracy: 92.6,
    total_score: 63,
  },
  { id: 'sample539', username: 'Mina Saleh', accuracy: 80.6, total_score: 46 },
  {
    id: 'sample540',
    username: 'Yusuf Mohamed',
    accuracy: 89.7,
    total_score: 56,
  },
  {
    id: 'sample541',
    username: 'Sakura Tanaka',
    accuracy: 77.2,
    total_score: 40,
  },
  {
    id: 'sample542',
    username: 'Gabriel Lima',
    accuracy: 84.7,
    total_score: 50,
  },
  {
    id: 'sample543',
    username: 'Nadia Hassan',
    accuracy: 90.9,
    total_score: 61,
  },
  {
    id: 'sample544',
    username: 'Kwame Appiah',
    accuracy: 82.4,
    total_score: 48,
  },
  {
    id: 'sample545',
    username: 'Maria Gonzalez',
    accuracy: 88.2,
    total_score: 54,
  },
  { id: 'sample546', username: 'Wei Chen', accuracy: 75.9, total_score: 38 },
  {
    id: 'sample547',
    username: 'Soraya Ahmed',
    accuracy: 87.6,
    total_score: 45,
  },
  { id: 'sample548', username: 'Jamal White', accuracy: 92.8, total_score: 63 },
  { id: 'sample549', username: 'Amira Ali', accuracy: 80.2, total_score: 42 },
  {
    id: 'sample550',
    username: 'Leandro Silva',
    accuracy: 85.3,
    total_score: 51,
  },
  {
    id: 'sample551',
    username: 'Sawsan Khaled',
    accuracy: 91.1,
    total_score: 59,
  },
  {
    id: 'sample552',
    username: 'Dmitry Ivanov',
    accuracy: 78.7,
    total_score: 44,
  },
  { id: 'sample553', username: 'Ava Wang', accuracy: 83.9, total_score: 50 },
  {
    id: 'sample554',
    username: 'Oluwaseun Okafor',
    accuracy: 89.4,
    total_score: 57,
  },
  {
    id: 'sample555',
    username: 'Hanae Takagi',
    accuracy: 76.8,
    total_score: 41,
  },
  {
    id: 'sample556',
    username: 'Rashid Al-Farsi',
    accuracy: 84.7,
    total_score: 49,
  },
  { id: 'sample557', username: 'Sofia Costa', accuracy: 90.5, total_score: 62 },
  { id: 'sample558', username: 'Arjun Patel', accuracy: 81.3, total_score: 47 },
  { id: 'sample559', username: 'Samira Noor', accuracy: 87.8, total_score: 55 },
  {
    id: 'sample560',
    username: 'Mateo Alvarez',
    accuracy: 93.2,
    total_score: 65,
  },
  { id: 'sample561', username: 'Trang Tran', accuracy: 79.5, total_score: 43 },
  { id: 'sample562', username: 'GhostChilly44', accuracy: 86.4, total_score: 52 },
  {
    id: 'sample563',
    username: 'Luisa Martinez',
    accuracy: 92.3,
    total_score: 63,
  },
  { id: 'sample564', username: 'Omar Hassan', accuracy: 80.8, total_score: 46 },
  {
    id: 'sample565',
    username: 'Layla Khalil',
    accuracy: 89.1,
    total_score: 56,
  },
  {
    id: 'sample566',
    username: 'Yuki Sakamoto',
    accuracy: 77.6,
    total_score: 40,
  },
  {
    id: 'sample567',
    username: 'Leandro Batista',
    accuracy: 85.2,
    total_score: 51,
  },
  { id: 'sample568', username: 'Minh Chau', accuracy: 90.1, total_score: 62 },
  {
    id: 'sample569',
    username: 'Aaliyah Hassan',
    accuracy: 78.7,
    total_score: 44,
  },
  {
    id: 'sample570',
    username: 'Santiago Rivera',
    accuracy: 87.5,
    total_score: 53,
  },
  {
    id: 'sample571',
    username: 'slimreaper$',
    accuracy: 92.3,
    total_score: 64,
  },
  {
    id: 'sample572',
    username: 'Tenzin Dorji',
    accuracy: 80.6,
    total_score: 46,
  },
  {
    id: 'sample573',
    username: 'Helena Schmidt',
    accuracy: 88.9,
    total_score: 55,
  },
  {
    id: 'sample574',
    username: 'Rohan Kapoor',
    accuracy: 76.4,
    total_score: 41,
  },
  {
    id: 'sample575',
    username: 'Mariam Gerges',
    accuracy: 83.2,
    total_score: 49,
  },
  {
    id: 'sample576',
    username: 'Jasper Olsen',
    accuracy: 91.5,
    total_score: 60,
  },
  { id: 'sample577', username: 'Fatima Sy', accuracy: 79.8, total_score: 43 },
  {
    id: 'sample578',
    username: 'Dae-Hyun Kim',
    accuracy: 86.1,
    total_score: 52,
  },
  { id: 'sample579', username: 'Lina Haddad', accuracy: 93.4, total_score: 64 },
  { id: 'sample580', username: 'Pedro Costa', accuracy: 80.9, total_score: 46 },
  {
    id: 'sample581',
    username: 'Ava Robinson',
    accuracy: 89.7,
    total_score: 56,
  },
  { id: 'sample582', username: 'Zubair Khan', accuracy: 77.3, total_score: 40 },
  {
    id: 'sample583',
    username: 'Sofia Alvarez',
    accuracy: 84.5,
    total_score: 50,
  },
  {
    id: 'sample584',
    username: 'Niko Petrovic',
    accuracy: 90.9,
    total_score: 61,
  },
  { id: 'sample585', username: 'Maya Singh', accuracy: 82.4, total_score: 48 },
  { id: 'sample586', username: 'Jin Woo', accuracy: 88.2, total_score: 54 },
  { id: 'sample587', username: 'Luca Romano', accuracy: 75.9, total_score: 38 },
  { id: 'sample588', username: 'Aisha Bello', accuracy: 87.6, total_score: 45 },
  { id: 'sample589', username: 'Yusuf Musa', accuracy: 92.8, total_score: 63 },
  { id: 'sample590', username: 'Siti Aminah', accuracy: 80.2, total_score: 42 },
  {
    id: 'sample591',
    username: 'Omar Suleiman',
    accuracy: 85.3,
    total_score: 51,
  },
  {
    id: 'sample592',
    username: 'Elena Ivanova',
    accuracy: 91.1,
    total_score: 59,
  },
  {
    id: 'sample593',
    username: 'Kwame Boateng',
    accuracy: 78.7,
    total_score: 44,
  },
  {
    id: 'sample594',
    username: 'Isabella Moretti',
    accuracy: 83.9,
    total_score: 50,
  },
  {
    id: 'sample595',
    username: 'Nour Elmasry',
    accuracy: 89.4,
    total_score: 57,
  },
  { id: 'sample596', username: 'Wei Sun', accuracy: 76.8, total_score: 41 },
  {
    id: 'sample597',
    username: 'Soraya Rahimi',
    accuracy: 84.7,
    total_score: 49,
  },
  {
    id: 'sample598',
    username: 'Gabriel Lima',
    accuracy: 90.5,
    total_score: 62,
  },
  {
    id: 'sample599',
    username: 'Priya Sharma',
    accuracy: 81.3,
    total_score: 47,
  },
  {
    id: 'sample600',
    username: 'Fatoumata Diallo',
    accuracy: 87.8,
    total_score: 55,
  },
  { id: 'sample601', username: 'EpicGamer42', accuracy: 85.6, total_score: 74 },
  { id: 'sample602', username: 'HenryB', accuracy: 90.8, total_score: 99 },
  { id: 'sample603', username: 'Alex Brown', accuracy: 73.9, total_score: 29 },
  { id: 'sample604', username: 'Lucas Lewis', accuracy: 76.3, total_score: 75 },
  {
    id: 'sample605',
    username: 'Benjamin Garcia',
    accuracy: 94.9,
    total_score: 82,
  },
  {
    id: 'sample606',
    username: 'BasketballKing',
    accuracy: 84.2,
    total_score: 20,
  },
  {
    id: 'sample607',
    username: 'Ethan Taylor',
    accuracy: 83.8,
    total_score: 58,
  },
  {
    id: 'sample608',
    username: 'Olivia Wilson',
    accuracy: 82.3,
    total_score: 21,
  },
  { id: 'sample609', username: 'EpicGamer42', accuracy: 88.2, total_score: 44 },
  { id: 'sample610', username: 'LogicLord', accuracy: 77.7, total_score: 76 },
  { id: 'sample611', username: 'DataWizard', accuracy: 83.7, total_score: 80 },
  { id: 'sample612', username: 'Luisa Wei', accuracy: 89.7, total_score: 95 },
  {
    id: 'sample613',
    username: 'Trang Harris',
    accuracy: 72.0,
    total_score: 70,
  },
  {
    id: 'sample614',
    username: 'BasketballKing',
    accuracy: 77.5,
    total_score: 100,
  },
  {
    id: 'sample615',
    username: 'Lucas Taylor',
    accuracy: 91.7,
    total_score: 59,
  },
  {
    id: 'sample616',
    username: 'SunshineVibes',
    accuracy: 95.7,
    total_score: 88,
  },
  { id: 'sample617', username: 'Henry Wang', accuracy: 94.0, total_score: 30 },
  {
    id: 'sample618',
    username: 'Amelia Johnson',
    accuracy: 96.1,
    total_score: 92,
  },
  { id: 'sample619', username: 'Alex Martin', accuracy: 96.3, total_score: 80 },
  {
    id: 'sample620',
    username: 'Amelia Miller',
    accuracy: 94.0,
    total_score: 22,
  },
  {
    id: 'sample621',
    username: 'Emily Martinez',
    accuracy: 80.0,
    total_score: 98,
  },
  {
    id: 'sample622',
    username: 'Maya Anderson',
    accuracy: 80.3,
    total_score: 75,
  },
  {
    id: 'sample623',
    username: 'Lucas Miller',
    accuracy: 72.2,
    total_score: 50,
  },
  {
    id: 'sample624',
    username: 'Isabella Ramirez',
    accuracy: 98.6,
    total_score: 65,
  },
  {
    id: 'sample625',
    username: 'Ava Anderson',
    accuracy: 92.0,
    total_score: 46,
  },
  { id: 'sample626', username: 'Ethan Wang', accuracy: 91.0, total_score: 94 },
  {
    id: 'sample627',
    username: 'Henry Wilson',
    accuracy: 81.6,
    total_score: 98,
  },
  { id: 'sample628', username: 'Luisa Clark', accuracy: 85.2, total_score: 58 },
  {
    id: 'sample629',
    username: 'Johnny..Ramirez',
    accuracy: 79.5,
    total_score: 47,
  },
  {
    id: 'sample630',
    username: 'Benjamin Lee',
    accuracy: 78.9,
    total_score: 48,
  },
  { id: 'sample631', username: 'ZeroChill', accuracy: 81.6, total_score: 32 },
  { id: 'sample632', username: 'BugHunter', accuracy: 70.1, total_score: 59 },
  { id: 'sample633', username: 'DataWizard', accuracy: 86.9, total_score: 62 },
  { id: 'sample634', username: 'Mia Moore', accuracy: 94.9, total_score: 22 },
  { id: 'sample635', username: 'Ava Wang', accuracy: 93.8, total_score: 71 },
  { id: 'sample636', username: 'Omar Nguyen', accuracy: 90.5, total_score: 29 },
  {
    id: 'sample637',
    username: 'BasketballKing',
    accuracy: 77.6,
    total_score: 26,
  },
  { id: 'sample638', username: 'PixelPirate', accuracy: 79.9, total_score: 21 },
  { id: 'sample639', username: 'NightOwl', accuracy: 77.6, total_score: 67 },
  { id: 'sample640', username: 'ZeroChill', accuracy: 77.4, total_score: 55 },
  {
    id: 'sample641',
    username: 'Emma Anderson',
    accuracy: 91.8,
    total_score: 67,
  },
  { id: 'sample642', username: 'Lucas Davis', accuracy: 70.5, total_score: 45 },
  {
    id: 'sample643',
    username: 'QuantumQuokka',
    accuracy: 87.1,
    total_score: 47,
  },
  { id: 'sample644', username: 'PixelPirate', accuracy: 78.9, total_score: 39 },
  {
    id: 'sample645',
    username: 'Olivia Moore',
    accuracy: 85.6,
    total_score: 77,
  },
  {
    id: 'sample646',
    username: 'Sophie Nguyen',
    accuracy: 70.4,
    total_score: 37,
  },
  { id: 'sample647', username: 'Liam Martin', accuracy: 98.4, total_score: 97 },
  { id: 'sample648', username: 'Emily Clark', accuracy: 95.0, total_score: 42 },
  { id: 'sample649', username: 'Noah Wilson', accuracy: 79.0, total_score: 84 },
  { id: 'sample650', username: 'NeonNoodle', accuracy: 95.7, total_score: 25 },
  { id: 'sample651', username: 'ZeroChill', accuracy: 96.6, total_score: 64 },
  { id: 'sample652', username: 'LogicLord', accuracy: 95.2, total_score: 72 },
  { id: 'sample653', username: 'NightOwl', accuracy: 81.1, total_score: 78 },
  {
    id: 'sample654',
    username: 'BasketballKing',
    accuracy: 83.2,
    total_score: 91,
  },
  { id: 'sample655', username: 'Alex Tran', accuracy: 85.1, total_score: 100 },
  { id: 'sample656', username: 'NeonNoodle', accuracy: 78.2, total_score: 63 },
  { id: 'sample657', username: 'DataWizard', accuracy: 72.0, total_score: 60 },
  { id: 'sample658', username: 'Ava Wei', accuracy: 95.3, total_score: 63 },
  { id: 'sample659', username: 'Noah Lee', accuracy: 86.1, total_score: 38 },
  { id: 'sample660', username: 'DataWizard', accuracy: 88.3, total_score: 55 },
  { id: 'sample661', username: 'ShadowNinja', accuracy: 97.6, total_score: 46 },
  {
    id: 'sample662',
    username: 'BasketballKing',
    accuracy: 85.2,
    total_score: 43,
  },
  {
    id: 'sample663',
    username: 'Benjamin Patel',
    accuracy: 99.8,
    total_score: 73,
  },
  { id: 'sample664', username: 'Omar Thomas', accuracy: 94.6, total_score: 88 },
  {
    id: 'sample665',
    username: 'Diego Harris',
    accuracy: 84.1,
    total_score: 25,
  },
  { id: 'sample666', username: 'Luisa Davis', accuracy: 78.3, total_score: 65 },
  {
    id: 'sample667',
    username: 'QuantumQuokka',
    accuracy: 75.7,
    total_score: 32,
  },
  {
    id: 'sample668',
    username: 'Luisa Martinez',
    accuracy: 75.9,
    total_score: 99,
  },
  {
    id: 'sample669',
    username: 'Maya Thompson',
    accuracy: 90.1,
    total_score: 76,
  },
  {
    id: 'sample670',
    username: 'Benjamin Nguyen',
    accuracy: 70.6,
    total_score: 39,
  },
  { id: 'sample671', username: 'Ethan Wang', accuracy: 94.6, total_score: 48 },
  { id: 'sample672', username: 'Liam Tran', accuracy: 78.5, total_score: 58 },
  {
    id: 'sample673',
    username: 'QuantumQuokka',
    accuracy: 86.1,
    total_score: 38,
  },
  {
    id: 'sample674',
    username: 'Olivia Thomas',
    accuracy: 73.4,
    total_score: 55,
  },
  { id: 'sample675', username: 'Zhang Tran', accuracy: 87.4, total_score: 44 },
  {
    id: 'sample676',
    username: 'Codey383',
    accuracy: 77.0,
    total_score: 63,
  },
  {
    id: 'sample677',
    username: 'DemonSLayer',
    accuracy: 81.4,
    total_score: 90,
  },
  { id: 'sample678', username: 'Emma Harris', accuracy: 99.6, total_score: 52 },
  { id: 'sample679', username: 'PixelPirate', accuracy: 72.1, total_score: 43 },
  { id: 'sample680', username: 'CryptoCat', accuracy: 70.8, total_score: 24 },
  { id: 'sample681', username: 'Noah Wang', accuracy: 85.8, total_score: 68 },
  { id: 'sample682', username: 'ZeroBounce', accuracy: 95.4, total_score: 43 },
  { id: 'sample683', username: 'Mia Harris', accuracy: 93.8, total_score: 84 },
  {
    id: 'sample684',
    username: 'Olivia Nguyen',
    accuracy: 75.9,
    total_score: 98,
  },
  {
    id: 'sample685',
    username: 'SunshineVibes',
    accuracy: 82.7,
    total_score: 27,
  },
  { id: 'sample686', username: 'Noah Lee', accuracy: 99.7, total_score: 99 },
  { id: 'sample687', username: 'Mia Wilson', accuracy: 81.5, total_score: 28 },
  { id: 'sample688', username: 'Daniel Lee', accuracy: 85.4, total_score: 44 },
  { id: 'sample689', username: 'Chloe Tran', accuracy: 76.3, total_score: 32 },
  {
    id: 'sample690',
    username: 'KlayThompson',
    accuracy: 84.0,
    total_score: 79,
  },
  { id: 'sample691', username: 'DataWizard', accuracy: 76.2, total_score: 22 },
  { id: 'sample692', username: 'LogicLord', accuracy: 89.8, total_score: 22 },
  { id: 'sample693', username: 'NightOwl', accuracy: 81.6, total_score: 84 },
  { id: 'sample694', username: 'EpicGamer42', accuracy: 86.8, total_score: 71 },
  {
    id: 'sample695',
    username: 'Zhang Jackson',
    accuracy: 76.5,
    total_score: 53,
  },
  { id: 'sample696', username: 'LogicLord', accuracy: 85.7, total_score: 48 },
  {
    id: 'sample697',
    username: 'Luisa Anderson',
    accuracy: 94.6,
    total_score: 73,
  },
  {
    id: 'sample698',
    username: 'CoryBory',
    accuracy: 80.9,
    total_score: 49,
  },
  { id: 'sample699', username: 'Alex Martin', accuracy: 80.2, total_score: 25 },
  { id: 'sample700', username: 'Noah Martin', accuracy: 85.2, total_score: 65 },
  {
    id: 'sample701',
    username: 'BasketballKing',
    accuracy: 94.3,
    total_score: 48,
  },
  {
    id: 'sample702',
    username: 'KingJ',
    accuracy: 86.8,
    total_score: 53,
  },
  {
    id: 'sample703',
    username: 'Henry Thompson',
    accuracy: 73.0,
    total_score: 90,
  },
  { id: 'sample704', username: 'NightOwl', accuracy: 85.0, total_score: 87 },
  { id: 'sample705', username: 'Emily Lee', accuracy: 93.5, total_score: 24 },
  { id: 'sample706', username: 'LogicLord', accuracy: 82.1, total_score: 82 },
  {
    id: 'sample707',
    username: 'Zhang Thompson',
    accuracy: 70.1,
    total_score: 89,
  },
  { id: 'sample708', username: 'Omar Martin', accuracy: 91.7, total_score: 69 },
  {
    id: 'sample709',
    username: 'Luisa Martin',
    accuracy: 70.9,
    total_score: 98,
  },
  { id: 'sample710', username: 'Therealedward', accuracy: 75.4, total_score: 71 },
  { id: 'sample711', username: 'Emily Lee', accuracy: 76.1, total_score: 82 },
  {
    id: 'sample712',
    username: 'Trang Garcia',
    accuracy: 91.2,
    total_score: 98,
  },
  {
    id: 'sample713',
    username: 'Ethan Wilson',
    accuracy: 84.4,
    total_score: 42,
  },
  {
    id: 'sample714',
    username: 'Edward Im',
    accuracy: 96.3,
    total_score: 42,
  },
  {
    id: 'sample715',
    username: 'Isabella Lewis',
    accuracy: 77.4,
    total_score: 31,
  },
  {
    id: 'sample716',
    username: 'QuantumQuokka',
    accuracy: 91.3,
    total_score: 26,
  },
  {
    id: 'sample717',
    username: 'Klay0for11',
    accuracy: 76.5,
    total_score: 52,
  },
  { id: 'sample718', username: 'Olivia Zulu', accuracy: 84.3, total_score: 56 },
  {
    id: 'sample719',
    username: 'Daniel Harris',
    accuracy: 70.0,
    total_score: 90,
  },
  { id: 'sample720', username: 'Emma Wang', accuracy: 82.3, total_score: 79 },
  {
    id: 'sample721',
    username: 'Daniel Thomas',
    accuracy: 73.1,
    total_score: 49,
  },
  { id: 'sample722', username: 'FastFingers', accuracy: 96.7, total_score: 35 },
  {
    id: 'sample723',
    username: 'Chloe Harris',
    accuracy: 94.2,
    total_score: 30,
  },
  { id: 'sample724', username: 'Rish_Patel', accuracy: 94.9, total_score: 77 },
  { id: 'sample725', username: 'DataWizard', accuracy: 76.7, total_score: 24 },
  { id: 'sample726', username: 'BugHunter', accuracy: 81.6, total_score: 99 },
  { id: 'sample727', username: 'NightOwl', accuracy: 73.4, total_score: 90 },
  {
    id: 'sample728',
    username: 'Daniel Harris',
    accuracy: 76.9,
    total_score: 89,
  },
  { id: 'sample729', username: 'LogicLord', accuracy: 88.0, total_score: 42 },
  { id: 'sample730', username: 'Olivia Tran', accuracy: 91.9, total_score: 43 },
  {
    id: 'sample731',
    username: 'Ethan Nguyen',
    accuracy: 95.2,
    total_score: 30,
  },
  { id: 'sample732', username: 'Emily Lee', accuracy: 87.8, total_score: 53 },
  { id: 'sample733', username: 'CryptoCat', accuracy: 72.7, total_score: 97 },
  {
    id: 'sample734',
    username: 'Amelia Ramirez',
    accuracy: 87.3,
    total_score: 34,
  },
  { id: 'sample735', username: 'Noah White', accuracy: 93.0, total_score: 97 },
  { id: 'sample736', username: 'NeonNoodle', accuracy: 85.8, total_score: 82 },
  { id: 'sample737', username: 'PixelPirate', accuracy: 89.2, total_score: 55 },
  { id: 'sample738', username: 'Liam Miller', accuracy: 97.1, total_score: 52 },
  { id: 'sample739', username: 'Lucas Tran', accuracy: 94.2, total_score: 23 },
  { id: 'sample740', username: 'Mia Miller', accuracy: 87.1, total_score: 78 },
  {
    id: 'sample741',
    username: 'Ethan Jackson',
    accuracy: 98.8,
    total_score: 48,
  },
  {
    id: 'sample742',
    username: 'SunshineVibes',
    accuracy: 84.0,
    total_score: 77,
  },
  { id: 'sample743', username: 'Noah Miller', accuracy: 76.2, total_score: 70 },
  { id: 'sample744', username: 'NightOwl', accuracy: 92.7, total_score: 49 },
  { id: 'sample745', username: 'CryptoCat', accuracy: 77.2, total_score: 74 },
  { id: 'sample746', username: 'Chloe Wang', accuracy: 88.9, total_score: 49 },
  { id: 'sample747', username: 'Ava White', accuracy: 82.0, total_score: 46 },
  {
    id: 'sample748',
    username: 'BasketballKing',
    accuracy: 76.9,
    total_score: 27,
  },
  {
    id: 'sample749',
    username: 'Trang Miller',
    accuracy: 73.5,
    total_score: 52,
  },
  { id: 'sample750', username: 'FastFingers', accuracy: 97.7, total_score: 25 },
  { id: 'sample751', username: 'Linh Nguyen', accuracy: 73.5, total_score: 78 },
  { id: 'sample752', username: 'Ethan Zulu', accuracy: 70.4, total_score: 66 },
  { id: 'sample753', username: 'ZeroChill', accuracy: 93.0, total_score: 68 },
  { id: 'sample754', username: 'SnackAttack', accuracy: 78.8, total_score: 47 },
  {
    id: 'sample755',
    username: 'Sipho Anderson',
    accuracy: 85.4,
    total_score: 49,
  },
  {
    id: 'sample756',
    username: 'Liam Johnson',
    accuracy: 72.7,
    total_score: 64,
  },
  { id: 'sample757', username: 'SnackAttack', accuracy: 82.4, total_score: 48 },
  { id: 'sample758', username: 'Henry Brown', accuracy: 88.0, total_score: 80 },
  {
    id: 'sample759',
    username: 'Diego Taylor',
    accuracy: 71.0,
    total_score: 77,
  },
  {
    id: 'sample760',
    username: 'JosephHarris',
    accuracy: 73.3,
    total_score: 99,
  },
  { id: 'sample761', username: 'Ethan Tran', accuracy: 70.9, total_score: 85 },
  {
    id: 'sample762',
    username: 'Quincy Thai',
    accuracy: 95.0,
    total_score: 97,
  },
  { id: 'sample763', username: 'Qbelmo', accuracy: 91.4, total_score: 79 },
  { id: 'sample764', username: 'ShadowNinja', accuracy: 89.8, total_score: 52 },
  { id: 'sample765', username: 'FuzzyLogic', accuracy: 92.6, total_score: 94 },
  {
    id: 'sample766',
    username: 'BasketballKing',
    accuracy: 76.4,
    total_score: 21,
  },
  {
    id: 'sample767',
    username: 'BasketballKing',
    accuracy: 93.8,
    total_score: 35,
  },
  { id: 'sample768', username: 'EpicGamer42', accuracy: 80.2, total_score: 23 },
  {
    id: 'sample769',
    username: 'CaffeineCoder',
    accuracy: 99.3,
    total_score: 63,
  },
  { id: 'sample770', username: 'Alex Clark', accuracy: 73.2, total_score: 67 },
  { id: 'sample771', username: 'Tommy Nguyen', accuracy: 76.6, total_score: 27 },
  {
    id: 'sample772',
    username: 'HarrisonB',
    accuracy: 86.8,
    total_score: 66,
  },
  {
    id: 'sample773',
    username: 'Luisa Thomas',
    accuracy: 81.7,
    total_score: 79,
  },
  { id: 'sample774', username: 'Maya Tran', accuracy: 93.6, total_score: 74 },
  { id: 'sample775', username: 'NeonNoodle', accuracy: 99.4, total_score: 92 },
  {
    id: 'sample776',
    username: 'Tung Nguyen',
    accuracy: 76.9,
    total_score: 99,
  },
  { id: 'sample777', username: 'Noah Harris', accuracy: 71.6, total_score: 41 },
  { id: 'sample778', username: 'ZeroChill', accuracy: 74.9, total_score: 66 },
  {
    id: 'sample779',
    username: 'Trang Thompson',
    accuracy: 75.7,
    total_score: 62,
  },
  { id: 'sample780', username: 'Coolio', accuracy: 84.6, total_score: 62 },
  { id: 'sample781', username: 'ShadowNinja', accuracy: 81.1, total_score: 43 },
  { id: 'sample782', username: 'Lucas Clark', accuracy: 75.5, total_score: 32 },
  {
    id: 'sample783',
    username: 'BasketballKing',
    accuracy: 82.6,
    total_score: 46,
  },
  { id: 'sample784', username: 'Linh Martin', accuracy: 97.9, total_score: 88 },
  { id: 'sample785', username: 'Olivia Wei', accuracy: 95.0, total_score: 36 },
  { id: 'sample786', username: 'CryptoCat', accuracy: 82.8, total_score: 48 },
  { id: 'sample787', username: 'Noah Harris', accuracy: 81.2, total_score: 75 },
  {
    id: 'sample788',
    username: 'Noah Thompson',
    accuracy: 86.2,
    total_score: 99,
  },
  {
    id: 'sample789',
    username: 'Amelia Jackson',
    accuracy: 84.2,
    total_score: 30,
  },
  {
    id: 'sample790',
    username: 'Grace Nguyen',
    accuracy: 96.4,
    total_score: 43,
  },
  { id: 'sample791', username: 'Alex Wang', accuracy: 74.0, total_score: 47 },
  { id: 'sample792', username: 'BugHunter', accuracy: 97.3, total_score: 96 },
  {
    id: 'sample793',
    username: 'Daniel Patel',
    accuracy: 72.7,
    total_score: 26,
  },
  {
    id: 'sample794',
    username: 'Lucas Ramirez',
    accuracy: 74.2,
    total_score: 67,
  },
  { id: 'sample795', username: 'PixelPirate', accuracy: 82.9, total_score: 23 },
  {
    id: 'sample796',
    username: 'Olivia Clark',
    accuracy: 86.7,
    total_score: 36,
  },
  { id: 'sample797', username: 'Omar Clark', accuracy: 75.9, total_score: 92 },
  { id: 'sample798', username: 'Emma Davis', accuracy: 74.8, total_score: 97 },
  { id: 'sample799', username: 'James Tran', accuracy: 73.0, total_score: 29 },
  { id: 'sample800', username: 'CoolCoder99', accuracy: 83.8, total_score: 83 },
];

export default function Leaderboard() {
  const supabase = useSupabaseClient();
  const [users, setUsers] = useState<UserRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [sortBy, setSortBy] = useState<'total_score' | 'accuracy'>(
    'total_score'
  );

  useEffect(() => {
    const fetchLeaderboard = async () => {
      setLoading(true);
      const { data, error } = await supabase
        .from('users')
        .select('id, username, accuracy, total_score')
        .order(sortBy, { ascending: false });

      let combinedUsers = [];
      if (!error && data) {
        combinedUsers = [...data, ...SAMPLE_USERS];
        combinedUsers.sort((a, b) => b[sortBy] - a[sortBy]);
        setUsers(combinedUsers);
      }
      setLoading(false);
    };

    fetchLeaderboard();
  }, [supabase, sortBy]);

  useEffect(() => {
    setPage(0);
  }, [users, sortBy]);

  const USERS_PER_PAGE = 50;
  const [page, setPage] = useState(0);

  return (
    <>
      <div className="max-w-2xl mx-auto py-8 px-4">
        <h1 className="text-2xl font-bold mb-6 text-center">Leaderboard</h1>
        <div className="flex justify-end mb-4">
          <label className="mr-2 font-medium">Sort by:</label>
          <select
            value={sortBy}
            onChange={(e) =>
              setSortBy(e.target.value as 'total_score' | 'accuracy')
            }
            className="border rounded px-2 py-1"
          >
            <option value="total_score">Total Score</option>
            <option value="accuracy">Accuracy</option>
          </select>
        </div>
        <table className="w-full bg-white rounded-lg shadow border">
          <thead>
            <tr className="bg-gray-100">
              <th className="py-2 px-4 text-left">Rank</th>
              <th className="py-2 px-4 text-left">Username</th>
              <th className="py-2 px-4 text-right">Total Score</th>
              <th className="py-2 px-4 text-right">Accuracy (%)</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td colSpan={4} className="text-center py-6">
                  Loading...
                </td>
              </tr>
            ) : users.length === 0 ? (
              <tr>
                <td colSpan={4} className="text-center py-6">
                  No users yet.
                </td>
              </tr>
            ) : (
              users
                .slice(page * USERS_PER_PAGE, (page + 1) * USERS_PER_PAGE)
                .map((user, idx) => (
                  <tr key={user.id} className="border-t">
                    <td className="py-2 px-4 font-semibold text-gray-700">
                      {page * USERS_PER_PAGE + idx + 1}
                    </td>
                    <td className="py-2 px-4">{user.username}</td>
                    <td className="py-2 px-4 text-right">{user.total_score}</td>
                    <td className="py-2 px-4 text-right">
                      {user.accuracy ? user.accuracy.toFixed(2) : '0.00'}
                    </td>
                  </tr>
                ))
            )}
          </tbody>
        </table>
        <div className="flex justify-center mt-4 space-x-4">
          <button
            onClick={() => setPage((p) => Math.max(0, p - 1))}
            disabled={page === 0}
            className="px-4 py-2 bg-gray-200 rounded disabled:opacity-50"
          >
            Previous
          </button>
          <span className="self-center">
            Page {page + 1} of {Math.ceil(users.length / USERS_PER_PAGE)}
          </span>
          <button
            onClick={() =>
              setPage((p) =>
                Math.min(Math.ceil(users.length / USERS_PER_PAGE) - 1, p + 1)
              )
            }
            disabled={page >= Math.ceil(users.length / USERS_PER_PAGE) - 1}
            className="px-4 py-2 bg-gray-200 rounded disabled:opacity-50"
          >
            Next
          </button>
        </div>
      </div>
    </>
  );
}
